### ISSUE TITLE
Please tag version 1.2.1

### ISSUE THREAD

**Issue by neogic** [vanderlee/tristate#12]
Thanks for the great plugin! Please tag v1.2.1 to latest commit so that can be used with jsDelivr.net etc :)  Thanks!

**Comment by neogic** [comment]
Update - pull request created to make it easy! https://github.com/vanderlee/tristate/pull/13

**Comment by vanderlee** [comment]
Done.

**Comment by neogic** [comment]
Awesome, thanks Martijn! :)
