### ISSUE TITLE
The necessity of jQuery UI dependency

### ISSUE THREAD

**Issue by arteezy** [vanderlee/tristate#5]
I was looking for tristate checkbox jQuery plugin, found this project and this is exactly what I needed. I almost ended up using it, until I saw jQuery UI requirement. Woah! I don't want to drag this fat library just for one small altered checkbox. It's a dealbreaker for me.

Is jQuery UI absolutely needed here?

**Comment by vanderlee** [comment]
jQuery UI is primarily needed to deal with releasing memory. It should be quite possible to remove the dependancy, but it would require careful coding and testing.

**Comment by vanderlee** [comment]
A wee bit late, but I've finally gotten to remove the jQueryUI requirement. I've also tested if for memory leaks and checked the unittest, and all seems okay.
