### ISSUE TITLE
Cycle Order = indeterminate, checked, unchecked?

### ISSUE THREAD

**Issue by JamoCA** [vanderlee/tristate#9]
This is more of a feature extension than an issue.

How difficult would it be to add an option to change the switch order of the toggles?  Currently it goes from "indeterminate to unchecked" and sometimes it'd be more beneficial to instead go from "indeterminate to checked".

Thanks.

**Comment by vanderlee** [comment]
This shouldn't be too hard. I'll see if I can add some sort of `reverse` option.

**Comment by vanderlee** [comment]
I've added a `reverse` options. Could you please test and confirm?

**Comment by JamoCA** [comment]
It works perfectly.  Thanks again.  I'm not sure if this is the preferred/best practice, but it made more sense having it be initially toggle to "checked".
